version: '3'
services:

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: base-env

  python:
    container_name: python
    extends: base
    build:
      context: .
      dockerfile: Dockerfile.python
    image: dev-env-python
    ports:
      - "0.0.0.0:2223:22"
      - "0.0.0.0:8081:8080"
    dns:
      - 8.8.8.8

  rust:
    container_name: rust
    extends: base
    build:
      context: .
      dockerfile: Dockerfile.rust
    image: dev-env-rust
    ports:
      - "0.0.0.0:2222:22"
      - "0.0.0.0:8080:8080"
    dns:
      - 8.8.8.8
