FROM ubuntu:latest

RUN apt-get update && apt-get install -y sudo

RUN useradd -ms /bin/bash devuser -u 1000
RUN echo "devuser:password" | chpasswd
RUN echo 'devuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER devuser

RUN sudo apt-get install -y \
    git \
    make \
    bat \
    ripgrep \
    neovim \
    curl \
    neofetch \
    fd-find \
    net-tools \
    iproute2 \
    iputils-ping

RUN sudo apt-get install -y openssh-server
RUN sudo mkdir /var/run/sshd
EXPOSE 22
